Repository SAP/code-pal-for-abap, pull requests merged in 2020-08, with the labels that each got.

#66 Refactoring statement_for_message
  clean_code_main/clean_code_checks/y_check_base.clas.abap
  clean_code_main/clean_code_checks/y_check_call_method_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_chain_decl_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_check_stmnt_position.clas.abap
  clean_code_main/clean_code_checks/y_check_comment_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_constants_interface.clas.abap
  clean_code_main/clean_code_checks/y_check_cx_root_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_cyclomatic_complexity.clas.abap
  clean_code_main/clean_code_checks/y_check_declaration_in_if.clas.abap
  clean_code_main/clean_code_checks/y_check_deprecated_key_words.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_catches.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_procedures.clas.abap
  clean_code_main/clean_code_checks/y_check_equals_sign_chaining.clas.abap
  clean_code_main/clean_code_checks/y_check_form.clas.abap
  clean_code_main/clean_code_checks/y_check_function.clas.abap
  clean_code_main/clean_code_checks/y_check_is_interface_in_class.clas.abap
  clean_code_main/clean_code_checks/y_check_max_nesting_depth.clas.abap
  clean_code_main/clean_code_checks/y_check_method_output_param.clas.abap
  clean_code_main/clean_code_checks/y_check_method_return_bool.clas.abap
  clean_code_main/clean_code_checks/y_check_non_class_exception.clas.abap
  clean_code_main/clean_code_checks/y_check_num_exec_statements.clas.abap
  clean_code_main/clean_code_checks/y_check_num_public_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_number_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_number_events.clas.abap
  clean_code_main/clean_code_checks/y_check_number_interfaces.clas.abap
  clean_code_main/clean_code_checks/y_check_number_methods.clas.abap
  clean_code_main/clean_code_checks/y_check_receiving_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_test_seam_usage.clas.abap
Labels: enhancement

#67 Simplifying RAISE_ERROR
  clean_code_main/clean_code_checks/y_check_base.clas.abap
  clean_code_main/clean_code_checks/y_check_base.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_base.clas.xml
  clean_code_main/clean_code_checks/y_check_call_method_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_chain_decl_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_check_stmnt_position.clas.abap
  clean_code_main/clean_code_checks/y_check_comment_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_constants_interface.clas.abap
  clean_code_main/clean_code_checks/y_check_cx_root_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_cyclomatic_complexity.clas.abap
  clean_code_main/clean_code_checks/y_check_db_access_in_ut.clas.abap
  clean_code_main/clean_code_checks/y_check_declaration_in_if.clas.abap
  clean_code_main/clean_code_checks/y_check_deprecated_key_words.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_catches.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_if_branches.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_procedures.clas.abap
  clean_code_main/clean_code_checks/y_check_equals_sign_chaining.clas.abap
  clean_code_main/clean_code_checks/y_check_form.clas.abap
  clean_code_main/clean_code_checks/y_check_function.clas.abap
  clean_code_main/clean_code_checks/y_check_is_interface_in_class.clas.abap
  clean_code_main/clean_code_checks/y_check_magic_number.clas.abap
  clean_code_main/clean_code_checks/y_check_max_nesting_depth.clas.abap
  clean_code_main/clean_code_checks/y_check_method_output_param.clas.abap
  clean_code_main/clean_code_checks/y_check_method_return_bool.clas.abap
  clean_code_main/clean_code_checks/y_check_non_class_exception.clas.abap
  clean_code_main/clean_code_checks/y_check_num_exec_statements.clas.abap
  clean_code_main/clean_code_checks/y_check_num_output_parameter.clas.abap
  clean_code_main/clean_code_checks/y_check_num_public_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_number_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_number_events.clas.abap
  clean_code_main/clean_code_checks/y_check_number_interfaces.clas.abap
  clean_code_main/clean_code_checks/y_check_number_methods.clas.abap
  clean_code_main/clean_code_checks/y_check_receiving_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_sub_assign_read_table.clas.abap
  clean_code_main/clean_code_checks/y_check_test_seam_usage.clas.abap
Labels: enhancement

#75 prioritizing threshold instead of criticality
  clean_code_main/clean_code_checks/y_check_base.clas.abap
  clean_code_main/clean_code_checks/y_check_base.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_call_method_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_chain_decl_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_check_stmnt_position.clas.abap
  clean_code_main/clean_code_checks/y_check_comment_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_constants_interface.clas.abap
  clean_code_main/clean_code_checks/y_check_cx_root_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_cyclomatic_complexity.clas.abap
  clean_code_main/clean_code_checks/y_check_db_access_in_ut.clas.abap
  clean_code_main/clean_code_checks/y_check_declaration_in_if.clas.abap
  clean_code_main/clean_code_checks/y_check_deprecated_key_words.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_catches.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_if_branches.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_procedures.clas.abap
  clean_code_main/clean_code_checks/y_check_equals_sign_chaining.clas.abap
  clean_code_main/clean_code_checks/y_check_equals_sign_chaining.clas.xml
  clean_code_main/clean_code_checks/y_check_form.clas.abap
  clean_code_main/clean_code_checks/y_check_function.clas.abap
  clean_code_main/clean_code_checks/y_check_is_interface_in_class.clas.abap
  clean_code_main/clean_code_checks/y_check_magic_number.clas.abap
  clean_code_main/clean_code_checks/y_check_max_nesting_depth.clas.abap
  clean_code_main/clean_code_checks/y_check_method_output_param.clas.abap
  clean_code_main/clean_code_checks/y_check_method_return_bool.clas.abap
  clean_code_main/clean_code_checks/y_check_non_class_exception.clas.abap
  clean_code_main/clean_code_checks/y_check_num_exec_statements.clas.abap
  clean_code_main/clean_code_checks/y_check_num_output_parameter.clas.abap
  clean_code_main/clean_code_checks/y_check_num_public_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_number_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_number_events.clas.abap
  clean_code_main/clean_code_checks/y_check_number_interfaces.clas.abap
  clean_code_main/clean_code_checks/y_check_number_methods.clas.abap
  clean_code_main/clean_code_checks/y_check_pseudo_comment_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_receiving_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_sub_assign_read_table.clas.abap
  clean_code_main/clean_code_checks/y_check_test_seam_usage.clas.abap
  clean_code_main/clean_code_foundation/y_clean_code_manager.clas.abap
Labels: bug

#81 major changes
  clean_code_main/clean_code_checks/y_check_base.clas.abap
  clean_code_main/clean_code_checks/y_check_base.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_call_method_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_chain_decl_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_chain_decl_usage.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_check_stmnt_position.clas.abap
  clean_code_main/clean_code_checks/y_check_comment_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_constants_interface.clas.abap
  clean_code_main/clean_code_checks/y_check_cx_root_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_cyclomatic_complexity.clas.abap
  clean_code_main/clean_code_checks/y_check_cyclomatic_complexity.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_db_access_in_ut.clas.abap
  clean_code_main/clean_code_checks/y_check_declaration_in_if.clas.abap
  clean_code_main/clean_code_checks/y_check_deprecated_key_words.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_catches.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_if_branches.clas.abap
  clean_code_main/clean_code_checks/y_check_empty_procedures.clas.abap
  clean_code_main/clean_code_checks/y_check_equals_sign_chaining.clas.abap
  clean_code_main/clean_code_checks/y_check_equals_sign_chaining.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_form.clas.abap
  clean_code_main/clean_code_checks/y_check_function.clas.abap
  clean_code_main/clean_code_checks/y_check_is_interface_in_class.clas.abap
  clean_code_main/clean_code_checks/y_check_is_interface_in_class.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_magic_number.clas.abap
  clean_code_main/clean_code_checks/y_check_max_nesting_depth.clas.abap
  clean_code_main/clean_code_checks/y_check_method_output_param.clas.abap
  clean_code_main/clean_code_checks/y_check_method_return_bool.clas.abap
  clean_code_main/clean_code_checks/y_check_non_class_exception.clas.abap
  clean_code_main/clean_code_checks/y_check_num_exec_statements.clas.abap
  clean_code_main/clean_code_checks/y_check_num_exec_statements.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_num_output_parameter.clas.abap
  clean_code_main/clean_code_checks/y_check_num_output_parameter.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_num_public_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_num_public_attributes.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_number_attributes.clas.abap
  clean_code_main/clean_code_checks/y_check_number_attributes.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_number_events.clas.abap
  clean_code_main/clean_code_checks/y_check_number_events.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_number_interfaces.clas.abap
  clean_code_main/clean_code_checks/y_check_number_interfaces.clas.testclasses.abap
  clean_code_main/clean_code_checks/y_check_number_methods.clas.abap
  clean_code_main/clean_code_checks/y_check_pseudo_comment_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_receiving_usage.clas.abap
  clean_code_main/clean_code_checks/y_check_sub_assign_read_table.clas.abap
  clean_code_main/clean_code_checks/y_check_test_seam_usage.clas.abap
Labels: bug, enhancement

#90 Creating contribution guide
  CONTRIBUTING.md
Labels: documentation
